### ISSUE TITLE
Missing calculation methods

### ISSUE THREAD

**Issue by houssemko** [GoodM4ven/athan-gnome-shell-extension#12]
In our region we use the Karashi calculation method , and it's missing from the updated Gnome 47 extension .

**Comment by GoodM4ven** [comment]
Dang it. Is that a difference by 1 angle degree for Al-Isha' prayer?

**Comment by houssemko** [comment]
Nope I have no idea .

**Comment by GoodM4ven** [comment]
Submitted. Test it and tell me if it did the job or not.

**Comment by houssemko** [comment]
It's perfect , thank you
