### ISSUE TITLE
Ubuntu - light mode

### ISSUE THREAD

**Issue by baronleonardo** [GoodM4ven/athan-gnome-shell-extension#15]
![image](https://github.com/user-attachments/assets/ce68eabb-117f-4a97-bcee-bf1a7eb17e51)
this is the output on ubuntu light mode, the text is always white, whenever I'm on light or dark mode

**Comment by technology-maen** [comment]
I believe using `-st-accent-bg-color` instead of `-st-accent-fg-color` should fix it i could do a pr

**Comment by GoodM4ven** [comment]
> I believe using `-st-accent-bg-color` instead of `-st-accent-fg-color` should fix it i could do a pr i tested it on my machine and it looks good I'll send a screenshot later in sha allah

I apologize for the delay, I got married recently and I barely have time to touch the computer; may Allah get you all married, aameen!

I, however, checked yesterday the docs, and it seem to point what you said out. So it's all yours, if you could test both cases, and it works, feel free to PR, brother.

**Comment by technology-maen** [comment]
Congratulations may Allah grant you happiness and unity in your marriage. I'll make a pr by the end of the day in sha allah as I'll be in school
