### ISSUE TITLE
Missing Calculations from The Egyptian General Authority of survey (الهيئة المصرية العامة للمساحة)

### ISSUE THREAD

**Issue by technology-maen** [GoodM4ven/athan-gnome-shell-extension#16]
just as the title says

**Comment by GoodM4ven** [comment]
Can you PR for this one too?
It should be very simple, as I had minimized the extension from before:
https://github.com/a7medkhalaf/azan-gnome-shell-extension/commit/734ef1f44afd02e1fe94193fd363bb112db06d18#diff-30037de3cb91645373dc355373718f9040861649b025e9b0837bd086d01a83a2

Click on show the diff in the [PrayTimes.js] file.

**Comment by technology-maen** [comment]
ok

**Comment by technology-maen** [comment]
done

**Comment by GoodM4ven** [comment]
May Allah reward you.
I'll submit the changes to gnome.org immediately, in sha'a Allah.
