### ISSUE TITLE
no notifications when it's time to pray

### ISSUE THREAD

**Issue by houssemko** [GoodM4ven/athan-gnome-shell-extension#2]
the extension doesn't notify before the prayer time comes.

**Comment by GoodM4ven** [comment]
@houssemko I've already submitted a quick change to Gnome Shell Extensions, which was discussed here #1 . I'm using the patch locally and I'll keep you updated in case it had fixed the issue. The only drawback, however, is that we've lost the position customization for now...

**Comment by GoodM4ven** [comment]
Can confirm that the patch works for the "before athan notification." Still need to test the actual prayer's.

![image](https://github.com/GoodM4ven/athan-gnome-shell-extension/assets/121377476/7945ef5d-6a0c-4dd8-99c3-6f7731e9ccb2)

**Comment by GoodM4ven** [comment]
Praise be to Allah, it has finally worked. It will be the upcoming v6 today, in sha' Allah, @houssemko .

![image](https://github.com/GoodM4ven/athan-gnome-shell-extension/assets/121377476/cad49e9d-fd10-4150-badb-a19747cf1053)

**Comment by houssemko** [comment]
thank you for your work .
