### ISSUE TITLE
Translation compilation warnings

### ISSUE THREAD

**Issue by GoodM4ven** [GoodM4ven/athan-gnome-shell-extension#21]
- A duplicate entry
- A non-ASCII or whatever thing, which I think they mean `\u2019` (right single quote) character

**Comment by abdoei** [comment]
Could you please give me more details about that? It doesn't give me any warning about the duplicate entry thing. And yeah, in Arabic, we use `،` not `,` for separation.

**Comment by GoodM4ven** [comment]
For some reason, the warnings aren't showing anymore! As I'm using your modified #22 Makefile as well as the last rework pushed to `master`.

جزاك الله خيرا .
