### ISSUE TITLE
Can you increase the contrast between the text font color and the background ?

### ISSUE THREAD

**Issue by houssemko** [GoodM4ven/athan-gnome-shell-extension#5]
The prayer time is hard to read from a distance . 
The solution in my opinion to make the font white .

**Comment by GoodM4ven** [comment]
Is this okay, @houssemko ?

![image](https://github.com/GoodM4ven/athan-gnome-shell-extension/assets/121377476/25a0da9e-7cc0-4ba3-9b9b-f34465610db1)

**Comment by houssemko** [comment]
yes that would be good , thank you.

**Comment by GoodM4ven** [comment]
Incoming v8

**Comment by houssemko** [comment]
great .
