### ISSUE TITLE
Calculation Method

### ISSUE THREAD

**Issue by biinci** [GoodM4ven/athan-gnome-shell-extension#6]
In the country I live in, the calculation method used is 'The Presidency of Religious Affairs of Turkey,' but this option is not available in the application. Could you please add it?

**Comment by GoodM4ven** [comment]
I don't think anything extra is needed, @biinci . Here's a picture that explains it all:


I have done the following:

- I've checked their timing as seen on the site.
- Hard-coded coordinates for a random location in Ankara, for instance.
- Set calculation method to `MWL`.
- Ensured the timezone is `+3 GMT`.

-Everything in the image, basically, and it seems to match the exact prayer times.

**Comment by biinci** [comment]
I had left the location services on automatic; I should have adjusted them myself. Everything works fine now that I've adjusted it. Thank you for this wonderful application. I apologize for my mistake.

**Comment by GoodM4ven** [comment]
It's alright. And I'm not the one who coded the JS prayer-times calculator nor the whole extension. This is just a **fork** of a lot of previous iterations on top of the original extension repository... I just made it work for Gnome v46, is all.

And, as always, all thanks and appraisals are to Allah only; for guiding us to pray to him even. (الحمد لله)
