### ISSUE TITLE
Gnome 47 support 

### ISSUE THREAD

**Issue by sal0-h** [GoodM4ven/athan-gnome-shell-extension#7]
Assalamu Aleykum. 
After updating to a newer version of gnome I get this:

![Screenshot From 2024-09-21 13-12-46](https://github.com/user-attachments/assets/5bb188c6-4ebd-4ea2-8fb8-34c82cce1c2e)

Will the new version be supported? This is gnome 47.

**Comment by AbdulRahmanMassarani** [comment]
wa3alykum alsalam wara7mato allah wa barakatoh
i am not involved in this project as such I do
n't know whether this project will support gnome 47 however I have a suggestion
how about as a stopgap measure until this extension supports gnome 47 you use an app like the flathub app munadi?
it has an option in it's settings to stay minimized in the panel after you exit the app and can start minimized on startup

![Screenshot from 2024-09-21 17-16-32](https://github.com/user-attachments/assets/1f6d5b47-1ddd-4202-b971-b9b2edeec2a2)
![Screenshot from 2024-09-21 17-17-15](https://github.com/user-attachments/assets/a7024dc1-4d69-4a4a-b9be-bc81be0b4674)

**Comment by GoodM4ven** [comment]
I'm working on a separate version for 47, in sha'a Allah.

**Comment by GoodM4ven** [comment]
Submitted version 9 (with GNOME 47 support) for review.
